--Atividade prática de laboratório a partir do banco de dados fornecido em aula
--Listar os vendedores ativos ordenados pelo nome.
SELECT * FROM TB_VENDEDOR WHERE ATIVO='S' ORDER BY NOME;

--Listar as vendas realizadas via APP.
SELECT * FROM TB_VENDA WHERE CANAL='APP';

--Calcular o valor total vendido por cada vendedor.
SELECT VEND.ID_VENDEDOR, VEND.NOME, SUM(VEN.VALOR_LIQUIDO) AS TOTAL FROM TB_VENDEDOR VEND JOIN TB_VENDA VEN ON VEND.ID_VENDEDOR=VEN.ID_VENDEDOR GROUP BY VEND.ID_VENDEDOR, VEND.NOME ORDER BY TOTAL DESC;

--Listar os clientes que possuem vendas canceladas.
SELECT DISTINCT CLI.NOME FROM TB_CLIENTE CLI JOIN TB_VENDA VEN ON CLI.ID_CLIENTE=VEN.ID_CLIENTE WHERE STATUS='CANCELADA';

--Identificar o cliente com o maior valor total de compras.
SELECT CLI.ID_CLIENTE, CLI.NOME, SUM(VEN.VALOR_LIQUIDO) AS TOTAL FROM TB_CLIENTE CLI JOIN TB_VENDA VEN ON CLI.ID_CLIENTE=VEN.ID_CLIENTE GROUP BY CLI.ID_CLIENTE, CLI.NOME ORDER BY TOTAL DESC FETCH FIRST 1 ROW ONLY;